<html>
  <head>
    <meta content="text/html; charset=UTF-8">
    <meta name="keywords" content="DiscoGAN">
    <meta name="description" content="Free Web DiscoGAN">
    <meta name="author" content="Kimyounghoon">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to DiscoGAN</title>
  </head>
  <body>

  <?php

    $name = $_POST['name'];

    $image = $_FILES['sreenshot']['name'];
    $target = './input/'.$image;
    $sreenshot_type = $_FILES['sreenshot']['type'];
    $sreenshot_size = $_FILES['sreenshot']['size'];
    $tmp_name = $_FILES['sreenshot']['tmp_name'];
    $error = $_FILES['sreenshot']['error'];

    move_uploaded_file($tmp_name, $target);

    $source = "./input/".$image;
    $destination = "./output/".$image;

    try{
    exec("python ../load_image.py "
    //C:/Users/Public/AppData/Local/Continuum/anaconda3/python
    .$source.' '.$destination.' '.$_POST['dataset'], $output);


    }catch(exception $e){
      echo $e;
    }

    echo "<h2>Create new thing!</h2>";
    echo "your input ";
    echo '<img src="./output/'.$image.'_A.jpg"></br>';

    echo "your output";
    echo '<img src="./output/'.$image.'_AB.jpg">';
    #echo phpinfo();
   ?>

   <hr>
   <div>
   This was generated by computer.</br>
   You may not be satisfied with the results.</br>
   But the results will <b>improve</b> in the further.
  </div>
  </body>
<html>
